# Generated by Django 6.0.3 on 2026-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_screen_time', models.IntegerField()),
                ('app_sessions', models.IntegerField()),
                ('social_media_usage', models.IntegerField()),
                ('gaming_time', models.IntegerField()),
                ('notifications', models.IntegerField()),
                ('night_usage', models.IntegerField()),
                ('age', models.IntegerField()),
                ('work_study_hours', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('apps_installed', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
